import os
from fastapi import Request, HTTPException
from fastapi.responses import HTMLResponse
from typing import Any
from backend.CONSTANTS import *
from backend.documents import ALL_DOCUMENTS
from backend.tools import *
from backend.template_setup import templates, jenv
import jinja2
import mistune
import cohere
from cohere.types import SystemChatMessageV2, UserChatMessageV2, AssistantChatMessageV2, ChatMessages, ToolChatMessageV2

# helper function to check if a template exists in pages dir
def template_exists(template_name: str) -> bool:
    html_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.html")
    md_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.md")
    return os.path.isfile(html_path) or os.path.isfile(md_path)

# helper function to return template path given basename
def get_template_path(template_name: str) -> str:
    html_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.html") # "pages/chatbot.html", relative to templates directory
    md_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.md")
    if os.path.isfile(html_path): # return relative path
        return RELATIVE_PATH_PAGES_DIR + "/" + f"{template_name}.html"
    elif os.path.isfile(TEMPLATE_DIR / md_path): # return full path since md files have to be read manually
        return md_path
    else:
        return "" # for pydantic

# helper function to render template  with context given basename and request
def render_template(template_name: str, request: Request) -> HTMLResponse:
    if not template_exists(template_name):
        raise HTTPException(status_code=404, detail="Template not found")  
    context : dict[str, Request | Any ] = {
        "request": request,
        "files": os.listdir(FULL_PATH_PAGES_DIR),
        "currentPage": template_name
    }
    name = get_template_path(template_name)
    try: # try to render .html
        return templates.TemplateResponse(request=request, name=name, context=context, headers=HEADERS)
    except jinja2.TemplateNotFound: # assuming markdown
        # read from file and convert markdown to html
        with open(FULL_PATH_PAGES_DIR / name, "r", encoding="utf-8") as f:
            content = f.read()
            md = mistune.html(content)
            assert type(md) == str, "Expected mistune to return a string of HTML"
            md = "{% extends 'base.html' %}\n{% block content %}" + md + "\n{% endblock %}"
            rendered_html = jenv.from_string(md).render(context)
            return HTMLResponse(content=rendered_html, headers=HEADERS)
        
# make api call to cohere with user message and return context dict for rendering
# request only required so we can return in dict
def chat(user_message: str, request: Request) -> dict[str, Any]:
    assert COHERE_API_KEY is not None, "Cohere API key not found. Please set the COHERE_API_KEY environment variable."
    co = cohere.ClientV2(api_key=COHERE_API_KEY)

    messages : ChatMessages = [
        SystemChatMessageV2(content=PROMPT),
        UserChatMessageV2(content=user_message),
    ]

    response = co.chat(
        model="command-a-03-2025",
        messages=messages,
        documents=ALL_DOCUMENTS,
        # tools=[describe_tool]
        # citation_options=CitationOptions(mode="accurate"),
    )

    tool_calls_made: list[str] = []

    if response.message.tool_calls:
        for tool_call in response.message.tool_calls:
            assert tool_call.function != None
            if tool_call.function.name == "describe_macon_statistics":
                tool_calls_made.append("describe_macon_statistics")
                tool_results = describe().to_dict()
                messages.append(AssistantChatMessageV2(tool_calls=[tool_call]))
                messages.append(ToolChatMessageV2(tool_call_id=tool_call.id, content=str(tool_results)))
                
        response = co.chat(
            model="command-a-03-2025",
            messages=messages,
            documents=ALL_DOCUMENTS,
            tools=[describe_tool]
        )

    # Extract text response
    responses = response.message.content
    assert responses is not None and len(responses) > 0, "No response generated by the AI."
    first_response = responses[0]
    assert first_response.type == "text", f"Expected a text response, but got {first_response.type}"
    ai_response = first_response.text

    # Extract unique cited sources from citations
    seen_doc_ids: set[str] = set()
    citations: list[dict[str, str]] = []
    raw_citations = response.message.citations or []
    for citation in raw_citations:
        for source in (citation.sources or []):
            if source.type == "document":
                doc_id = source.id or ""
                if doc_id not in seen_doc_ids:
                    seen_doc_ids.add(doc_id)
                    doc_data = source.document or {}
                    title = doc_data.get("title", "Source")
                    url = doc_data.get("url", "")
                    if url:
                        citations.append({"title": title, "url": url})

    # Add the user message and AI response to the chat history
    messages.append(UserChatMessageV2(content=user_message))  # todo: add length/security checks
    messages.append(AssistantChatMessageV2(content=ai_response))

    context: dict[str, Request | Any] = {
        "request": request,
        "user_message": user_message,
        "ai_message": ai_response,
        "citations": citations,
        "tool_calls_made": tool_calls_made
    }

    return context