import os
from fastapi import Request, HTTPException
from fastapi.responses import HTMLResponse
from typing import Any
from backend.CONSTANTS import *
from backend.tools import *
from backend.template_setup import templates, jenv
import jinja2
import mistune
import cohere
from cohere.types import SystemChatMessageV2, UserChatMessageV2, AssistantChatMessageV2, ChatMessages, ToolChatMessageV2, Document
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
import langchain_core.documents.base as langchain_documents

import re
from markitdown import MarkItDown

# helper function to check if a template exists in pages dir
def template_exists(template_name: str) -> bool:
    html_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.html")
    md_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.md")
    return os.path.isfile(html_path) or os.path.isfile(md_path)

# helper function to return template path given basename
def get_template_path(template_name: str) -> str:
    html_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.html") # "pages/chatbot.html", relative to templates directory
    md_path = os.path.join(FULL_PATH_PAGES_DIR, f"{template_name}.md")
    if os.path.isfile(html_path): # return relative path
        return RELATIVE_PATH_PAGES_DIR + "/" + f"{template_name}.html"
    elif os.path.isfile(TEMPLATE_DIR / md_path): # return full path since md files have to be read manually
        return md_path
    else:
        return "" # for pydantic

# helper function to render template  with context given basename and request
def render_template(template_name: str, request: Request) -> HTMLResponse:
    if not template_exists(template_name):
        raise HTTPException(status_code=404, detail="Template not found")  
    context : dict[str, Request | Any ] = {
        "request": request,
        "files": os.listdir(FULL_PATH_PAGES_DIR),
        "currentPage": template_name
    }
    name = get_template_path(template_name)
    try: # try to render .html
        return templates.TemplateResponse(request=request, name=name, context=context, headers=HEADERS)
    except jinja2.TemplateNotFound: # assuming markdown
        # read from file and convert markdown to html
        with open(FULL_PATH_PAGES_DIR / name, "r", encoding="utf-8") as f:
            content = f.read()
            md = mistune.html(content)
            assert type(md) == str, "Expected mistune to return a string of HTML"
            md = "{% extends 'base.html' %}\n{% block content %}" + md + "\n{% endblock %}"
            rendered_html = jenv.from_string(md).render(context)
            return HTMLResponse(content=rendered_html, headers=HEADERS)
        
# make api call to cohere with user message and return context dict for rendering
# request only required so we can return in dict
def chat(user_message: str, request: Request, documents: list[Document]) -> dict[str, Any]:
    assert COHERE_API_KEY is not None, "Cohere API key not found. Please set the COHERE_API_KEY environment variable."
    co = cohere.ClientV2(api_key=COHERE_API_KEY)

    messages : ChatMessages = [
        SystemChatMessageV2(content=PROMPT),
        UserChatMessageV2(content=user_message),
    ]

    response = co.chat(
        model="command-a-03-2025",
        messages=messages,
        documents=documents[0:200],
        # tools=[describe_tool]
        # citation_options=CitationOptions(mode="accurate"),
    )

    tool_calls_made: list[str] = []

    if response.message.tool_calls:
        for tool_call in response.message.tool_calls:
            assert tool_call.function != None
            if tool_call.function.name == "describe_macon_statistics":
                tool_calls_made.append("describe_macon_statistics")
                tool_results = describe().to_dict()
                messages.append(AssistantChatMessageV2(tool_calls=[tool_call]))
                messages.append(ToolChatMessageV2(tool_call_id=tool_call.id, content=str(tool_results)))
                
        response = co.chat(
            model="command-a-03-2025",
            messages=messages,
            documents=documents,
            tools=[describe_tool]
        )

    # Extract text response
    responses = response.message.content
    assert responses is not None and len(responses) > 0, "No response generated by the AI."
    first_response = responses[0]
    assert first_response.type == "text", f"Expected a text response, but got {first_response.type}"
    ai_response = first_response.text

    # Extract unique cited sources from citations
    seen_doc_ids: set[str] = set()
    citations: list[dict[str, str]] = []
    raw_citations = response.message.citations or []
    for citation in raw_citations:
        for source in (citation.sources or []):
            if source.type == "document":
                doc_id = source.id or ""
                if doc_id not in seen_doc_ids:
                    seen_doc_ids.add(doc_id)
                    doc_data = source.document or {}
                    title = doc_data.get("title", "Source")
                    url = doc_data.get("url", "")
                    if url:
                        citations.append({"title": title, "url": url})

    # Add the user message and AI response to the chat history
    messages.append(UserChatMessageV2(content=user_message))  # todo: add length/security checks
    messages.append(SystemChatMessageV2(content=ai_response))

    context: dict[str, Request | Any] = {
        "request": request,
        "user_message": user_message,
        "ai_message": ai_response,
        "citations": citations,
        "tool_calls_made": tool_calls_made
    }

    return context

def slug(text: str) -> str:
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text

def chunk_markdown_from_url(url: str, title: str, description: str = "", id: str = "", chunk_size: int = TEXT_SPLITTER_CHUNK_SIZE, chunk_overlap: int = TEXT_SPLITTER_CHUNK_OVERLAP) -> list[cohere.types.Document]:
    return chunk_markdown_from_file(path=url, web_url=url,    title=title, description=description, id=id, chunk_size=chunk_size, chunk_overlap=chunk_overlap)

def chunk_markdown_from_file(path: str, web_url: str, title: str, description: str = "", id: str = "", chunk_size: int = TEXT_SPLITTER_CHUNK_SIZE, chunk_overlap: int = TEXT_SPLITTER_CHUNK_OVERLAP) -> list[cohere.types.Document]:
    match Path(path).suffix:
        case ".md":
            with open(path, "r", encoding="utf-8") as doc:
                contents = doc.read()
                return chunk_markdown_from_string(contents, web_url, title, description, id, chunk_size, chunk_overlap)
        case ".pdf" | ".html":
            md = MarkItDown().convert(path) # also works with urls
            return chunk_markdown_from_string(md.text_content, web_url, title, description, id, chunk_size, chunk_overlap)
        case _:
            raise NotImplementedError(f"Unsupported file type for path {path} with suffix {Path(path).suffix}")


# return list of documents (chunks of markdown) from one source, each with the same metadata
def chunk_markdown_from_string(md_string: str, web_url: str, title: str, description: str = "", id: str = "", chunk_size: int = TEXT_SPLITTER_CHUNK_SIZE, chunk_overlap: int = TEXT_SPLITTER_CHUNK_OVERLAP) -> list[cohere.types.Document]:
    if id == "":
        id = slug(title)

    headers : list[tuple[str, str]] = [
        ("#", "Header 1"),
        ("##", "Header 2"),
        ("###", "Header 3"),
        ("####", "Header 4"),
        ("#####", "Header 5"),
        ("######", "Header 6"),
    ]

    md_splitter = MarkdownHeaderTextSplitter(headers)
    documents : list[langchain_documents.Document] = md_splitter.split_text(md_string)

    
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    documents = text_splitter.split_documents(documents=documents)
    
    # TODO: use, embed / rerank models instead of sending documents to chat model
    return [cohere.types.Document(
        id = f"{id}_chunk_{i}",
        data={
            "text": doc.page_content,
            "url": web_url,
            "title": title,
            **({"description": description} if description else {})
        } 
    ) for i, doc in enumerate(documents) ]